# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14cf1902a2e1968c87e4538495ae5fd773a440ad31518d9a77d44caa22f2428db17dda096a3220c8e5e9f32e822121f9419b94fafc9e16d8cc6e6e0c915c662e

test:
  secret_key_base: 6f9471422b236be00dd1adfb180fcd2c34745e3530c393ab91bf155bfcef000dcfa845f650ec4f09ceb01d263b36682b15de201336b52fd39b7aa050f7eab3c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
